<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJxbAJ3c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJxbAJ3c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJxbAJ3c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJxbAJ3c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJxbAJ3c\App_KernelDevDebugContainer([
    'container.build_hash' => 'JxbAJ3c',
    'container.build_id' => '87c1cfb6',
    'container.build_time' => 1686753093,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJxbAJ3c');
