<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerJs7bTCw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJs7bTCw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJs7bTCw.legacy');
=======
if (\class_exists(\ContainerJxbAJ3c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJxbAJ3c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJxbAJ3c.legacy');
>>>>>>> ad5541920edc77322732f04634bef5d26b11c59b

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerJs7bTCw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJs7bTCw\App_KernelDevDebugContainer([
    'container.build_hash' => 'Js7bTCw',
    'container.build_id' => 'ccf07d37',
    'container.build_time' => 1686750069,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJs7bTCw');
=======
    \class_alias(\ContainerJxbAJ3c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJxbAJ3c\App_KernelDevDebugContainer([
    'container.build_hash' => 'JxbAJ3c',
    'container.build_id' => '87c1cfb6',
    'container.build_time' => 1686753093,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJxbAJ3c');
>>>>>>> ad5541920edc77322732f04634bef5d26b11c59b
