<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0DrR381\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0DrR381/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0DrR381.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0DrR381\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0DrR381\App_KernelDevDebugContainer([
    'container.build_hash' => '0DrR381',
    'container.build_id' => 'bde933e1',
    'container.build_time' => 1686580542,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0DrR381');
