<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXWQrBLZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXWQrBLZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXWQrBLZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXWQrBLZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXWQrBLZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'XWQrBLZ',
    'container.build_id' => '278f5bfe',
    'container.build_time' => 1686746800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXWQrBLZ');
